### ISSUE TITLE
Getting invalid_auth error

### ISSUE THREAD

**Issue by amiregelz** [nikkothari22/firebase-slack-extension#1]
I installed the extension and setup a Slack app.
1. I am using the `xoxb` (Bot User OAuth Token).

2. I allowed these Bot Scopes:
[chat:write](https://api.slack.com/scopes/chat:write)
[chat:write.customize](https://api.slack.com/scopes/chat:write.customize)
[chat:write.public](https://api.slack.com/scopes/chat:write.public)
[incoming-webhook](https://api.slack.com/scopes/incoming-webhook)
[reactions:write](https://api.slack.com/scopes/reactions:write)
[users.profile:read](https://api.slack.com/scopes/users.profile:read)
 as well as access to the `firebase-notifications` channel.
 
 
However I'm consistently getting this error:
```
{
  "authToken": "xoxb-297............",
  "channel": "firebase-notifications",
  "message": {
    "text": "Hello from Firebase2"
  },
  "response": {
    "error": "invalid_auth",
    "ok": false,
    "response_metadata": {
      "warnings": [
        "missing_charset"
      ]
    },
    "warning": "missing_charset"
  },
  "status": "success",
  "updatedOn": {
    "__datatype__": "timestamp",
    "value": "2022-08-22T11:53:26.185Z"
  }
}
```

**Comment by amiregelz** [comment]
Maybe this could be relevant?
https://github.com/slackapi/python-slack-sdk/issues/302

**Comment by nikkothari22** [comment]
Hey @amiregelz ,

Can you test your token here: https://api.slack.com/methods/chat.postMessage/test ?

You can add your Bot token, Channel name and Text in the fields and see if it returns a positive response.

**Comment by amiregelz** [comment]
Hey @nikkothari22 ,
Yeah it works perfectly there.
Maybe the issue is the encoding of the request sent by the trigger?

**Comment by nikkothari22** [comment]
Hmm.. weird. I just tested from both the tester and the extension on a new project and it worked.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/19825455/185963236-01e57808-05b3-4427-aad8-bbf29743bc05.png">

**Comment by nikkothari22** [comment]
@amiregelz 
Is `firebase-notifications` a private channel? However, that will only return a `channel_not_found` error.

**Comment by amiregelz** [comment]
Ok I figured it out - I was adding the doc using Firefoo tool, which probably messed up with the encoding there. When I add it via code it works!
Thank you :)
